---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Docker
  when: "'docker-ce' not in ansible_facts.packages"
  become: true
  block:
    - include_tasks: install.yml
    - include_tasks: plugins.yml
