---
- name: Update stacks (on first swarm node)
  run_once: true
  block:
    - name: Verify stacks directory exists
      file:
        path: "/home/{{ ansible_user }}/stacks"
        state: directory

    - name: Install pip packages
      become: true
      apt:
        pkg:
          - python3-jsondiff
          - python3-yaml
        state: present

    - import_tasks: traefik.yml