---
- name: Verify if traefik directory exists
  file:
    path: "/home/{{ ansible_user }}/stacks/traefik"
    state: directory

- name: Verify if traefik GFS directory exists
  become: true
  file:
    path: "{{ gluster_mount_path }}/traefik"
    state: directory

- name: Create Traefik stack file
  template:
    src: traefik/stack.j2.yml
    dest: /home/{{ ansible_user }}/stacks/traefik/stack.yml
    mode: 0755

- name: Create Traefik config file
  template:
    src: traefik/dynamic.j2.yml
    dest: /home/{{ ansible_user }}/stacks/traefik/dynamic.yml
    mode: 0755

- name: Create Traefik stack file
  template:
    src: traefik/traefik-public.j2.yml
    dest: /home/{{ ansible_user }}/stacks/traefik/traefik-public.yml
    mode: 0755

- name: Copy local Traefik certificates
  copy:
    src: traefik/local-certificates
    dest: /home/{{ ansible_user }}/stacks/traefik

- name: Deploy stack
  community.docker.docker_stack:
    state: present
    name: traefik
    compose:
      - /home/{{ ansible_user }}/stacks/traefik/stack.yml