# Dynamic configuration
http:
  middlewares:
    secure-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: 'SAMEORIGIN'
        customResponseHeaders: # remove unnessesary headers which expose used server software
          server: ''
          x-powered-by: ''
    lan-whitelist:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32
          - 192.168.0.0/16

tls:
  options:
    default:
      minVersion: VersionTLS12
  stores:
    default:
      defaultCertificate:
        certFile: /run/secrets/global.crt
        keyFile: /run/secrets/global.key