---

- name: Check if Gluster plugin has already been initialized
  shell: docker plugin inspect glusterfs
  register: gluster_plugin_status
  ignore_errors: true

- name: Update GlusterFS plugin
  when: gluster_plugin_status.rc == 0
  block:
    - name: Disable Docker Gluster plugin
      shell: docker plugin disable -f glusterfs

    - name: Install Docker Gluster plugin
      shell: docker plugin upgrade --grant-all-permissions glusterfs trajano/glusterfs-volume-plugin

    - name: Set Gluster plugin to use Gluster nodes
      shell: docker plugin set glusterfs SERVERS={{ groups['gluster_nodes'] | join(",") }}

    - name: Enable Gluster plugin
      shell: docker plugin enable glusterfs
