---

- name: Get info on docker host
  community.docker.docker_host_info:
  register: docker_info

- name: Add Docker node to existing Swarm as worker
  shell: docker swarm join --token {{ hostvars[groups['swarm_managers'][0]]['worker_token']['stdout'] }} [{{ groups['swarm_managers'][0] }}]:2377
  # Only join swarm when node is not already part of a swarm.
  when: docker_info.host_info.Swarm.LocalNodeState != 'active'

