---
- name: Set firewall rules for proxy
  become: true
  block:
    - name: Allow HTTP connections from the public web
      community.general.ufw:
        rule: allow
        port: 80

    - name: Allow HTTP connections from the public web
      community.general.ufw:
        rule: allow
        port: 443

    - name: Allow Wireguard connections from the public web
      community.general.ufw:
        rule: allow
        port: 51820
