---
- name: Set up nginx
  become: true
  block:
    - name: Install nginx
      ansible.builtin.package:
        name:
          - nginx
          - libnginx-mod-stream 
        state: present

    - name: Configure nginx
      ansible.builtin.template:
        src: nginx.j2.conf
        dest: /etc/nginx/nginx.conf
        mode: "0644"
        owner: root
        group: root

    - name: Reload nginx config
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: reloaded
