---
- name: Allow GlusterFS communication among nodes (trusted pool)
  become: true
  community.general.ufw:
    rule: allow
    src: "{{ hostvars[item].inventory_hostname }}"
  when: item != inventory_hostname
  loop: "{{ groups['gluster_nodes'] }}"
