---

- hosts: all
  tasks:
    - include_vars: '{{ playbook_dir }}/config.yml'
    - import_role:
        name: default

- hosts: proxy
  tasks:
    - include_vars: '{{ playbook_dir }}/config.yml'
    - import_role:
        name: proxy

- hosts: swarm_managers
  tasks:
    - include_vars: '{{ playbook_dir }}/config.yml'
    - import_role:
        name: docker
    - import_role:
        name: swarm-manager

- hosts: swarm_workers
  tasks:
    - include_vars: '{{ playbook_dir }}/config.yml'
    - import_role:
        name: docker
    - import_role:
        name: swarm-worker

- hosts: gluster_nodes
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: gluster
    - import_role:
        name: gluster-volume
