---

- hosts: all
  tasks:
    - include_vars: '{{ playbook_dir }}/config.yml'
    - import_role:
        name: default

- hosts: swarm_managers
  tasks:
    - include_vars: '{{ playbook_dir }}/config.yml'
    - import_role:
        name: docker
    - import_role:
        name: swarm-manager

- hosts: swarm_workers
  tasks:
    - include_vars: '{{ playbook_dir }}/config.yml'
    - import_role:
        name: docker
